### PR TITLE
ephemeral storage resources

### PR DESCRIPTION
**Pull request by beorereleverion**
this PR resolve https://github.com/hashicorp/vault-k8s/issues/361 and https://github.com/hashicorp/vault-k8s/issues/310

### CODE REVIEW

**Comment by beorereleverion** [comment]
Hello. Can anyone  review this pr?

**Comment by apolubotko** [comment]
Hi, 

We have been waiting for this change for a very long time, we will be very happy to see it in the master branch

**Comment by beorereleverion** [comment]
@tvoran @swenson Hello, can you review this pr? please

**Review by tomhjp — APPROVED** [review]
Thanks for implementing this! I gave it a test run and it all worked really nicely, with just one tiny bug where the flags specifying the defaults weren't being threaded through. I also added a little changelog note, just to save a trivial review round.

**Comment by Kyslik** [comment]
This seems to be _breaking change_ :(. Can you also include a note in the docs that you have/should to specify `resources.limits.ephemeral-storage` for **all containers** in the pod otherwise you are risking to have your pods evicted more in https://github.com/kubernetes/kubernetes/blob/v1.25.0/pkg/kubelet/eviction/eviction_manager.go#L453-L479

> Although you can only specify requests and limits for individual containers, it is also useful to think about the overall resource requests and limits for a Pod. For a particular resource, a Pod resource request/limit is the sum of the resource requests/limits of that type for each container in the Pod.

From https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage

---

Using ENV variable (`AGENT_INJECT_EPHEMERAL_LIMIT `) one can not disable `ephemeral-storage` limits either, because how the checks for default are implemented. The only option is to use annotation `vault.hashicorp.com/agent-limits-ephemeral` which is not ideal, because you have to update all your deployments...

**Comment by tomhjp** [comment]
Thanks @Kyslik, apologies for the inconvenience. I think #386 should fix this by defaulting the ephemeral storage resources to unset, so it will then only be an explicitly opt-in feature.

**Comment by Kyslik** [comment]
> Thanks @Kyslik, apologies for the inconvenience. I think #386 should fix this by defaulting the ephemeral storage resources to unset, so it will then only be an explicitly opt-in feature. Feel free to leave any comments you have in the review.

No worries; we learned something new here :). Thank you.

**Pull request merged**
