### PR TITLE
Add Auth Mount Path Config (Env / Annotation)

### PR DESCRIPTION
**Pull request by shlee322**
### Method 1. Set sidecar-injector container environment variable
```yaml
- name: AGENT_INJECT_VAULT_AUTH_PATH
  value: "auth/kubernetes"
```

### Method 2. Add target pod annotation
```yaml
vault.hashicorp.com/auth-path: "auth/kubernetes"
```

### CODE REVIEW

**Comment by joemiller** [comment]
We would also like to see the auth mount path configurable. However, it would be preferable (in our case) for it to be configurable in the agent-inject webhook

Use case:
- Vault instance serving multiple kubernetes clusters.
- Each k8s cluster is registered at a different mount path, eg:
1. `/auth/k8s-cluster01`
2. `/auth/k8s-cluster02`
3. `/auth/k8s-cluster03`
- Applications do not know what cluster they're deployed into, and may be deployed to multiple clusters.
- These apps' deployment yaml's should not need any cluster-specific information in them, so specifying the auth mount path in the pod's annotations would not be ideal here.
- The agent-inject webhook (ideally) would be deployed into each cluster with a config option specifying the auth path relevant to that cluster, eg: `https://$VAULT_ADDR` + `/auth/k8s-cluster01`
- The agent config file generated by the agent-injector would set the auth_auth section with the correct mount path for the current k8s cluster

**Comment by joemiller** [comment]
_(deleted previous comment, as i misread this as a feature request not an open PR, apologies)_

Would love to see this merged! Thank you for this, we have this same use case / need.

**Comment by carnei-ro** [comment]
The same use case here! Thanks for implementing it.

**Comment by izhukov** [comment]
Also hit the lack of this feature. We use the external vault with several kubernetes auth backends.
@shlee322 much appreciated your effort

**Comment by devorbitus** [comment]
This feature would really help us when it is merged

**Comment by jesseaukeman** [comment]
Lack of this feature is also blocking our use.  I assume this environment variable will be added as part of the  vault-helm chart and the default configurable in the chart values.yaml?

**Comment by Mark-McCracken** [comment]
Now that this is merged, can someone perform a release to dockerhub to update this so we can use it without having to build ourselves?

**Comment by Mark-McCracken** [comment]
I tested this last night, works like a charm with multiple clusters :)
Thanks so much for this @shlee322 that's so much easier than having to use a custom configmap!

**Comment by jasonodonnell** [comment]
Released in `v0.2.0`.  Hope that helps!

**Comment by Mark-McCracken** [comment]
Thanks so much :)

**Pull request merged**
